--- #YAML:1.0
name:                Attribute-Tie
version:             0.01
abstract:            Tie via Attribute
license:             ~
author:              
    - Dan Kogai <dankogai@dan.co.jp>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
